host = "https://www.ikanmh.top"

user-agent = """
Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) \
AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 \
Mobile/15E148 Safari/604.1\
"""

output = "./output"
page = "./page"

[books.lodge]
title = "寄宿日記"
path = "/book/479"

[books.min]
title = "小妾"
path = "/book/506"

[books.noise]
title = "深夜噪音"
path = "/book/478"

[books.bulkhead]
title = "隔壁的她"
path = "/book/520"